const CONTROL_DATA_ENUM_1GEN = {
  //1세대
  SLOT_DOOR_LOCK: "SLOTLOCK", //슬롯 잠금
  SLOT_DOOR_UNLOCK: "SLOTUNLOCK", //슬롯 잠금 해제
  SLOT_BATTERY_UNLOCK: "PACKDISPOSE", //강제 배출
  SLOT_DOOR_OPEN: "SLOTOPEN", // 슬롯 개방
  SLOT_RESET: "SLOTRESET",
  SLOT_ALL_LOCK: "LOCKALL",//전체 슬롯 잠금
  SLOT_ALL_UNLOCK: "UNLOCKALL",//젠체 슬롯 잠금 해제
  AUTHRESET: "AUTHRESET",//인증 초기화
  BSSON: "BSSON", // 정보 갱신
  BSSRESET: "BSSRESET", // 리셋

}

type CONTROL_DATA_ENUM_1GEN = typeof CONTROL_DATA_ENUM_1GEN[keyof typeof CONTROL_DATA_ENUM_1GEN];
export default CONTROL_DATA_ENUM_1GEN;
// export {CONTROL_DATA_ENUM};