const IF_DATA_ENUM = {
  BSS_AGGREGATE : "IF-DATA-003",
  BSS_CHASSIS : "IF-DATA-004",
  BSS_SLOT : "IF-DATA-005",
  BSS_NFC : "IF-DATA-006",
  BSS_CHARGER : "IF-DATA-007",
  BATTERY_EXCHANGE : "IF-DATA-008",
  BATTERY_ANALYSIS : "IF-DATA-009",
  BATTERY_INSERTION : "IF-DATA-010",
  BATTERY_RELEASE : "IF-DATA-011",
  BSS_BATTERY : "IF-DATA-016",
}

type IF_DATA_ENUM = typeof IF_DATA_ENUM[keyof typeof IF_DATA_ENUM];
export default IF_DATA_ENUM;