export type DeviceListData = {
  flagYN?: string;
  grpCode?: string;
  grpName?: string;
  sysCode?: string;
  sysName?: string;
  deviceId?: string;
  dvcName?: string;
  compName?: string;
  compCode?: string;
  brchName?: string;
  brchCode?: string;
  alert?: string;
  connection?: string;
  network?: string;
  modelName?: string;
  modelCode?: string;
  step?: string;
  country?: string;
  city?: string;
  state?: string;
  zipcode?: string;
  street?: string;
  street2?: string;
  email?: string;
  firstName?: string;
  lastName?: string;
  latitude?: number | string;
  longitude?: number | string;
  instDate?: string | Date;
  createDate?: string | Date;
  batterySn?: string;
  batteryCode?: string;
  inverterSn?: string;
  inverterCode?: string;
  bmsVersion?: string;
  dcdcVersion?: string;
  rmdVersion?: string;
  bmaNumber?: string | number;
  inverterBrand?: string;
  inverterModel?: string;
  inverterFw?: string;
};
